version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: electronic_rfm_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: electronic_rfm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: electronic_rfm_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin      

volumes:
  pgdata:
  pgadmin_data:
