version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: sales_2023_2024
  
  - name: mart
    schema: public_analytics
    tables:
      - name: mart_rfm_features
  
  - name: model
    schema: public_model
    tables:
      - name: customer_clusters

  - name: analytics
    schema: public_analytics
    tables:
      - name: customer_clustered_information


      